# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
{{- if .Values.kubeclient.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kubeclient-dep
  labels:
    app: {{ .Release.Name }}-kubeclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kubeclient
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kubeclient
    spec:
      shareProcessNamespace: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
      - name: wait-for-broker-initcontainer
        image: {{ .Values.busyboxImage.repository }}/{{ .Values.busyboxImage.name }}:{{ .Values.busyboxImage.tag }}
        imagePullPolicy: {{ .Values.busyboxImage.pullPolicy }}
        command: ["/bin/sh", "-c", "until nc -vz broker.{{ .Release.Namespace }}.svc.cluster.local 1883; do sleep 1; done"]
        securityContext:
          {{ include "defaultContainerSecurityContext" . | indent 10 }}
      - name: wait-for-web-initcontainer
        image: {{ .Values.busyboxImage.repository }}/{{ .Values.busyboxImage.name }}:{{ .Values.busyboxImage.tag }}
        imagePullPolicy: {{ .Values.busyboxImage.pullPolicy }}
        command: ["/bin/sh", "-c", "until wget -q --spider http://web.{{ .Release.Namespace }}.svc.cluster.local; do sleep 1; done"]
        securityContext:
          {{ include "defaultContainerSecurityContext" . | indent 10 }}
      containers:
        - args:
          - --shell
          - /home/scenescape/SceneScape/manage.py
          - kubecommand
          - --broker
          - broker.{{ .Release.Namespace }}.svc.cluster.local
          - --resturl
          - https://web.{{ .Release.Namespace }}.svc.cluster.local/api/v1
          - --ntp
          - ntpserv.{{ .Release.Namespace }}.svc.cluster.local
          - --auth
          - /run/secrets/auth/controller.auth
          image: {{ .Values.repository }}/{{ .Values.kubeclient.image }}:{{ .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.kubeclient.pullPolicy }}
          name: {{ .Release.Name }}-kubeclient
          env:
          - name: MODEL_CONFIGS_FOLDER
            value: "/data/models/model_configs"
          - name: KUBERNETES_NAMESPACE
            value: {{ .Release.Namespace }}
          - name: HELM_RELEASE
            value: {{ .Release.Name }}
          - name: HELM_REPO
            value: {{ .Values.kubeclient.vaPipeline.repository }}
          - name: HELM_IMAGE
            value: {{ .Values.kubeclient.vaPipeline.image }}
          - name: HELM_TAG
            value: {{ .Values.kubeclient.vaPipeline.tag }}
          - name: HELM_PULL_POLICY
            value: {{ .Values.kubeclient.vaPipeline.pullPolicy }}
          {{- with .Values.imagePullSecrets }}
          {{- range $index, $pullSecret := . }}
          - name: KUBERNETES_PULL_SECRET_{{ $index }}
            value: {{ $pullSecret.name | quote }}
          {{- end }}
          {{- end }}
          {{ include "proxy_envs" . | indent 10 }}
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            periodSeconds: 1
          resources: {}
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: false
          volumeMounts:
          - mountPath: /run/secrets/certs
            name: certs
            readOnly: true
          - mountPath: /run/secrets/django/secrets.py
            subPath: secrets.py
            name: secrets-py
            readOnly: true
          - mountPath: /run/secrets/auth
            name: auth
            readOnly: true
          - mountPath: /data
            name: models-storage
            readOnly: true
      restartPolicy: Always
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-kubeclient-sa
      volumes:
      {{ include "certs_volume" . | indent 6 }}
      - name: secrets-py
        secret:
          secretName: {{ .Release.Name }}-secrets-py
      - name: auth
        secret:
          secretName: {{ .Release.Name }}-controller.auth
      - name: models-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-models-pvc
status: {}
{{ end }}
