# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ntp-dep
  labels:
    app: {{ .Release.Name }}-ntpserv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ntpserv
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ntpserv
    spec:
      shareProcessNamespace: true
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      initContainers:
        - command:
          - sh
          - -c
          - touch /tmp/healthy
          image: {{ .Values.busyboxImage.repository }}/{{ .Values.busyboxImage.name }}:{{ .Values.busyboxImage.tag }}
          imagePullPolicy: {{ .Values.busyboxImage.pullPolicy }}
          name: init-healthy-file
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          volumeMounts:
          - name: healthy-file
            mountPath: /tmp
      containers:
        - image: {{ .Values.ntpserv.image.repository }}/{{ .Values.ntpserv.image.name }}:{{ .Values.ntpserv.image.tag }}
          imagePullPolicy: {{ .Values.ntpserv.image.pullPolicy }}
          name: {{ .Release.Name }}-ntpserv
          env:
          - name: NTP_SERVERS
            value: {{ .Values.ntpserv.ntpServers }}
            {{ include "proxy_envs" . | indent 10 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - SETGID
                - SETUID
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
          ports:
          - containerPort: 123
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            periodSeconds: 1
          volumeMounts:
          - name: healthy-file
            mountPath: /tmp
          - name: etc-chrony
            mountPath: /etc/chrony
          - name: run-chrony
            mountPath: /run/chrony
          - name: var-lib-chrony
            mountPath: /var/lib/chrony
          resources: {}
      restartPolicy: Always
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: healthy-file
        emptyDir: {}
      - name: etc-chrony
        emptyDir:
          medium: Memory
      - name: run-chrony
        emptyDir:
          medium: Memory
      - name: var-lib-chrony
        emptyDir:
          medium: Memory
