# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-migrations-pvc
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "{{ int .Values.pvc.hookWeight }}"
spec:
  storageClassName: {{ .Values.migrations.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.migrations.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-models-pvc
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "{{ int .Values.pvc.hookWeight }}"
spec:
  storageClassName: {{ .Values.video.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.video.storage }}
