# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pgserver
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: {{ .Release.Name }}-pgserver
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: pgserver
spec:
  selector:
    app: {{ .Release.Name }}-pgserver
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
