# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-pgserver
  labels:
    app: {{ .Release.Name }}-pgserver
  annotations:
    container.apparmor.security.beta.kubernetes.io/pgserver: unconfined
spec:
  serviceName: {{ .Release.Name }}-pgserver
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pgserver
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pgserver
    spec:
      shareProcessNamespace: true
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: {{ .Release.Name }}-pgserver
          image: {{ .Values.pgserver.repository }}/{{ .Values.pgserver.image }}:{{ .Values.pgserver.tag}}
          imagePullPolicy: {{ .Values.pgserver.pullPolicy }}
          env:
            - name: POSTGRES_USER
              value: "scenescape"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db
                  key: DATABASE_PASSWORD
            - name: POSTGRES_DB
              value: "scenescape"
              {{ include "proxy_envs" . | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgserver-storage
              subPath: pgdata
            - mountPath: /workspace/media
              name: media-storage
{{- if .Values.tests.enabled }}
            - mountPath: /workspace/tests
              name: tests-storage
              subPath: tests
{{- end }}
      restartPolicy: Always
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: dev-fuse
          hostPath:
            path: /dev/fuse
        - name: media-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-media-pvc
{{- if .Values.tests.enabled }}
        - name: tests-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-tests-pvc
{{- end }}
  volumeClaimTemplates:
  - metadata:
      name: pgserver-storage
    spec:
      storageClassName: {{ .Values.pvc.storageClassName }}
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.pgserver.storage }}
