---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "GitHub Actions"
    groups:
      github-actions-dependency:
        applies-to: version-updates
        patterns:
          - "*"
    reviewers:
      - "saratpoluri"
      - "dmytroye"
      - "tdorauintc"

  # Enable version updates for Helm charts
  - package-ecosystem: "helm"
    directories:
      - "/kubernetes/scenescape-chart"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Helm charts"
    reviewers:
      - "saratpoluri"
      - "dmytroye"
      - "tdorauintc"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/autocalibration"
      - "/broker"
      - "/controller"
      - "/kubernetes/init-images"
      - "/manager"
      - "/model_installer"
      - "/scene_common"
      - "/cluster_analytics"
      - "/controller/src/robot_vision"
      - "/mapping"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dockerfile"
    reviewers:
      - "saratpoluri"
      - "dmytroye"
      - "tdorauintc"

  # Enable version updates for Docker Compose
  - package-ecosystem: "docker-compose"
    directories:
      - "/sample_data"
      - "/tests/sscape_tests/detector"
      - "/tests/kubernetes/frp-test"
      - "/tests/compose"
      - "/tests/infra/rtsp-test"
      - "/tests/perf_tests/compose"
      - "/tests/security/libraries"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Docker Compose"
    reviewers:
      - "saratpoluri"
      - "dmytroye"
      - "tdorauintc"

  # Enable version updates for Python pip
  - package-ecosystem: "pip"
    directories:
      - "/.github/resources"
      - "/autocalibration"
      - "/autocalibration/src/reloc"
      - "/controller"
      - "/controller/src/robot_vision"
      - "/manager"
      - "/manager/test"
      - "/model_installer"
      - "/cluster_analytics"
      - "/mapping"
      - "/mapping/tests"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "pip"
    reviewers:
      - "saratpoluri"
      - "dmytroye"
      - "tdorauintc"
