# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = [
  "docs/doxygen/Doxyfile.common",
  "docs/doxygen/api_docs",
  "manager/src/static/site.webmanifest",
  "tests/security/fuzzing/token",
  "**/*.env",
  "**/mp4",
  "**/*.md",
  "**/*.json",
  "**/*.zip",
  "**/*.tar.bz2",
  "**/*.tar",
  "**/*.patch",
  "**/*.gltf",
  "**/*.glb",
  "**/*.gif",
  "**/*.ico",
  "**/*.png",
  "**/*.jpg",
  "**/*.JPG",
  "**/*.jpeg",
  "**/*.svg",
  "**/*.obj",
  "**/*.pdf",
  "**/*.conf",
  "**/*.cnf",
  "**/VERSION",
  ".github/ISSUE_TEMPLATE/*",
  ".gitignore",
  "**/.gitignore",
  "exclude_for_release.txt",
  "version.txt",
  "third-party-programs.txt",
  "**/*_data.txt",
  "**/*_json.txt"
]
precedence = "override"
SPDX-FileCopyrightText = "(C) 2025 Intel Corporation"
SPDX-License-Identifier = "Apache-2.0"
