# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-model-installer
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
data:
  copy-config-files: |-
{{ .Files.Get "files/model-installer/copy-config-files" | indent 4 }}
  install-omz-models: |-
{{ .Files.Get "files/model-installer/install-omz-models" | indent 4 }}
  generate_model_config.py: |-
{{ .Files.Get "files/model-installer/generate_model_config.py" | indent 4 }}
  requirements-runtime.txt: |-
{{ .Files.Get "files/model-installer/requirements-runtime.txt" | indent 4 }}
  person-detection-retail-0013.json: |-
{{ .Files.Get "files/model-installer/person-detection-retail-0013.json" | indent 4 }}
  model_config.json: |-
{{ .Files.Get "files/model-installer/model_config.json" | indent 4 }}
