---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

format: "table"
ignorefile: ".github/resources/sdl/.trivyignore.yaml"
scan:
  skip-files:
    - "scene_common/Dockerfile"
    - "tests/security/fuzzing/Dockerfile"
  skip-dirs:
    - ".github"
misconfiguration:
  helm:
    set:
      - supass=demo
      - pgserver.password=demo
