# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-retail-cams
  labels:
    app: {{ .Release.Name }}-retail-cams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-retail-cams
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-retail-cams
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      initContainers:
      - name: wait-for-rtsp
        image: {{ .Values.dlspsWaitImage.repository }}/{{ .Values.dlspsWaitImage.name }}:{{ .Values.dlspsWaitImage.tag }}
        imagePullPolicy: {{ .Values.dlspsWaitImage.pullPolicy }}
        command: ["sh", "-c", "until nc -z mediaserver 8554; do echo waiting for mediaserver; sleep 2; done"]
        securityContext:
          {{ include "defaultContainerSecurityContext" . | indent 10 }}
      containers:
      - name: retail-cams
        image: {{ .Values.retail.cameras.image }}:{{ .Values.retail.cameras.tag }}
        imagePullPolicy: {{.Values.retail.cameras.pullPolicy }}
        args: ["-nostdin", "-re", "-stream_loop", "-1", "-i", "/data/{{ index .Values.retail.cameras.files 0 }}", "-re", "-stream_loop", "-1", "-i", "/data/{{ index .Values.retail.cameras.files 1 }}", "-map", "0:v", "-c", "copy", "-f", "rtsp", "-rtsp_transport", "tcp", "rtsp://mediaserver:8554/retail-cam1", "-map", "1:v", "-c", "copy", "-f", "rtsp", "-rtsp_transport", "tcp", "rtsp://mediaserver:8554/retail-cam2"]
        volumeMounts:
        - name: sample-data
          mountPath: /data
          subPath: sample_data
      volumes:
      - name: sample-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-sample-data-pvc
      {{ include "certs_volume" . | indent 6 }}
