# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-broker
  labels:
    app: {{ .Release.Name }}-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-broker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-broker
    spec:
      securityContext:
        runAsUser: {{ .Values.broker.uid }}
        runAsGroup: {{ .Values.broker.gid }}
      containers:
        - name: broker
          image: {{ .Values.broker.image }}:{{ .Values.broker.tag }}
          imagePullPolicy: {{ .Values.broker.pullPolicy }}
          env:
            {{ include "proxy_envs" . | indent 12 }}
          ports:
            - containerPort: 1883
            - containerPort: 1884
          volumeMounts:
            - name: config-volume
              mountPath: /mosquitto/config
            - name: certs
              mountPath: /mosquitto/secrets/certs
          command: ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto-secure.conf"]
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-broker
            items:
              - key: mosquitto-secure.conf
                path: mosquitto-secure.conf
        {{- include "certs_volume" . | nindent 8 }}
