---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "[CI/CD] Build Docs"
run-name: "[CI/CD] Build Docs"

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch: {}

permissions:
  contents: read # needed for actions/checkout

jobs:
  filter:
    name: "Filter Changed Documentation Paths"
    runs-on: ubuntu-latest
    outputs:
      toplevel_changed: ${{ steps.filter.outputs.toplevel }}
      autocalibration_changed: ${{ steps.filter.outputs.autocalibration }}
      controller_changed: ${{ steps.filter.outputs.controller }}
      cluster_analytics_changed: ${{ steps.filter.outputs.cluster_analytics }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set paths filter
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          filters: |
            toplevel:
              - 'docs/**'
            autocalibration:
              - 'autocalibration/docs/**'
            controller:
              - 'controller/docs/**'
            cluster_analytics:
              - 'cluster_analytics/docs/**'

  build_toplevel:
    name: "Build Toplevel Documentation"
    needs: filter
    if: ${{ needs.filter.outputs.toplevel_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      exclude_patterns: "README.md, adr, design, development"

  build_autocalibration:
    name: "Build Autocalibration Documentation"
    needs: filter
    if: ${{ needs.filter.outputs.autocalibration_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: autocalibration

  build_controller:
    name: "Build Controller Documentation"
    needs: filter
    if: ${{ needs.filter.outputs.controller_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: controller

  cluster_analytics:
    name: "Build Cluster Analytics Documentation"
    needs: filter
    if: ${{ needs.filter.outputs.cluster_analytics_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: cluster_analytics
