---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "[Code Analysis] Trivy"
run-name: "[Code Analysis] Trivy"

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read # needed for actions/checkout

jobs:
  trivy-image-scan:
    name: "Build images and run Trivy image scan"
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: "Remove all Docker images"
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"
      - name: Install Trivy
        id: setup_trivy
        uses: aquasecurity/setup-trivy@e6c2c5e321ed9123bda567646e2f96565e34abe1 # v0.2.4
        with:
          version: "v0.68.2"
      - name: "Build images"
        id: build_images
        run: |
          echo "SCENESCAPE_VERSION=$(cat version.txt)" >> "$GITHUB_ENV"
          make build-all
          docker image ls | awk '{print $1 ":" $2}' | grep $(cat version.txt) | grep -v "\-test" > images.txt
      - name: "Run Trivy Image Scan"
        if: always() && steps.build_images.outcome == 'success' && steps.setup_trivy.outcome == 'success'
        run: |
          set +e
          EXIT_CODE=0
          cat images.txt || echo "No images found to scan."
          while read image; do
            echo "::group::Scanning image: $image"
            scan_name=$(echo $image | cut -f1 -d":")
            trivy image --config ".github/resources/sdl/trivy_config.yml" "$image"
            EXIT_CODE=$((EXIT_CODE || $?))
            echo "::endgroup::"
            if [ $EXIT_CODE -eq 1 ]; then
              echo "::error title=Trivy Image Scan Failed::Trivy scan found HIGH or CRITICAL vulnerabilities in image ${image}"
            fi
          done <<< $(cat images.txt)
          exit $EXIT_CODE

  trivy-critical-filesystem-scan:
    name: "Run Trivy Critical Filesystem Scan"
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Run Trivy Critical Filesystem Scan
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          version: "v0.68.2"
          scan-type: "fs"
          scan-ref: .
          trivy-config: ".github/resources/sdl/trivy_config.yml"
      - name: Create Error message if Vulnerabilities Found
        if: failure()
        run: |
          echo "::error title=Trivy Filesystem Scan Failed::Trivy scan found HIGH or CRITICAL vulnerabilities in the filesystem scan"
