---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "[Code Analysis] Trivy"
run-name: "[Code Analysis] Trivy"

on:
  schedule:
    - cron: "0 2 * * 0" # Every Sunday at 2:00 AM UTC
  workflow_call: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*
    types:
      - opened
      - synchronize
      - reopened

  # Trigger workflow when enqueued to a merge group
  # (must be under 'on')
  merge_group:

permissions:
  contents: read # needed for actions/checkout

jobs:
  trivy-image-scan:
    name: "Build images and run Trivy image scan"
    if: ${{ github.event_name == 'push' }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Install Trivy
        id: setup_trivy
        uses: aquasecurity/setup-trivy@e6c2c5e321ed9123bda567646e2f96565e34abe1 # v0.2.4
        with:
          version: "v0.65.0"
      - name: "Build images"
        id: build_images
        run: |
          git rev-parse HEAD > version.txt
          echo "SCENESCAPE_VERSION=$(cat version.txt)" >> "$GITHUB_ENV"
          make
          docker image ls | awk '{print $1 ":" $2}' | grep $(cat version.txt) | grep -v "\-test" > images.txt
      # Step name corrected from "Run Trivy Cirital/High Image Scan" to "Run Trivy Critical/High Image Scan".
      # Verified that no dependent processes rely on the old name.
      - name: "Run Trivy Image Scan"
        if: always() && steps.build_images.outcome == 'success' && steps.setup_trivy.outcome == 'success'
        run: |
          set +e
          EXIT_CODE=0
          cat images.txt || echo "No images found to scan."
          while read image; do
            echo "::group::Scanning image: $image"
            scan_name=$(echo $image | cut -f1 -d":")
            trivy image --list-all-pkgs --severity HIGH,CRITICAL --config ".github/resources/sdl/trivy_config.yml" --exit-code 1 "$image"
            echo "::endgroup::"
            EXIT_CODE=$((EXIT_CODE || $?))
            if [ $EXIT_CODE -eq 1 ]; then
              echo "::error title=Trivy Image Scan Failed::Trivy scan found HIGH or CRITICAL vulnerabilities in image ${image}"
            fi
          done <<< $(cat images.txt)
          exit $EXIT_CODE

  trivy-critical-filesystem-scan:
    name: "Run Trivy Critical Filesystem Scan"
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Run Trivy Critical Filesystem Scan
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          version: "v0.65.0"
          scan-type: "fs"
          scan-ref: .
          trivy-config: ".github/resources/sdl/trivy_config.yml"
          severity: "HIGH,CRITICAL"
          ignore-unfixed: false
          scanners: "vuln,misconfig,secret"
          exit-code: "1"
      - name: Create Error message if Vulnerabilities Found
        if: failure()
        run: |
          echo "::error title=Trivy Filesystem Scan Failed::Trivy scan found HIGH or CRITICAL vulnerabilities in the filesystem scan"
